db.url=jdbc:oracle:thin:@usatler01:1521/orclpdb.csl.local
db.username=ucompiere
db.password=ucompiere
1000000=\\Usatler01\\fr\\SOD Audit Report
1000001=\\Usatler01\\it\\SOD Audit Report
1000002=\\Usatler01\\pl\\SOD Audit Report
1000004=\\Usatler01\\nl\\SOD Audit Report
zip=\\Usatler01\\fr\\SOD Audit Report