db.url=jdbc:oracle:thin:@usatler01:1521/orclpdb.csl.local
db.username=ucompiere
db.password=ucompiere
excelFilePath=C:\Users\admin-rkarupak\Documents\Poland SMS\Service PID Load
sheetName=Global Service PID reviewed