package com.zoho.analytics.jdbc;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class ZohoAnalyticsConnection extends ZohoAnalyticsWrapper implements Connection {
   private ZohoAnalyticsMetaData analyticsMetaData;
   private boolean isClosed = false;
   private ArrayList<ZohoAnalyticsStatement> openStatements = new ArrayList();
   private ZohoAnalyticsAPI api;

   ZohoAnalyticsConnection(Properties props) throws SQLException {
      try {
         String organisationId = (String)props.get("ORG_ID");
         String workspaceName = (String)props.get("WORKSPACE_NAME");
         this.api = new ZohoAnalyticsAPI(props);
         this.analyticsMetaData = new ZohoAnalyticsMetaData(organisationId, workspaceName, this.api);
      } catch (SQLException var4) {
         throw var4;
      } catch (Exception var5) {
         throw (SQLException)(new SQLException(var5.getMessage())).initCause(var5);
      }
   }

   ZohoAnalyticsMetaData getAnalyticsMetaData() {
      return this.analyticsMetaData;
   }

   ZohoAnalyticsAPI getAnalyticsAPI() {
      return this.api;
   }

   void registerStatement(ZohoAnalyticsStatement stmt) {
      this.openStatements.add(stmt);
   }

   void unRegisterStatement(ZohoAnalyticsStatement stmt) {
      this.openStatements.remove(stmt);
   }

   public void clearWarnings() throws SQLException {
   }

   public void close() throws SQLException {
      try {
         if (!this.isClosed) {
            this.closeAllOpenStmts();
            this.isClosed = true;
         }
      } catch (Exception var2) {
         throw (SQLException)(new SQLException(var2.getMessage())).initCause(var2);
      }
   }

   private void closeAllOpenStmts() throws SQLException {
      while(this.openStatements.size() > 0) {
         ZohoAnalyticsStatement zrs = (ZohoAnalyticsStatement)this.openStatements.get(0);
         zrs.close(false);
         this.unRegisterStatement(zrs);
      }

   }

   public void commit() throws SQLException {
      throw new NotImplementedException();
   }

   public Statement createStatement() throws SQLException {
      this.checkClosed();
      Statement stmt = new ZohoAnalyticsStatement(this);
      return stmt;
   }

   public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
      throw new NotImplementedException();
   }

   public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
      throw new NotImplementedException();
   }

   public boolean getAutoCommit() throws SQLException {
      return true;
   }

   public String getCatalog() throws SQLException {
      return this.analyticsMetaData.getWorkspaceName();
   }

   public int getHoldability() throws SQLException {
      return 1;
   }

   public DatabaseMetaData getMetaData() throws SQLException {
      return new ZohoAnalyticsDatabaseMetadata(this);
   }

   public int getTransactionIsolation() throws SQLException {
      return 2;
   }

   public Map getTypeMap() throws SQLException {
      return new HashMap();
   }

   public SQLWarning getWarnings() throws SQLException {
      return null;
   }

   public boolean isClosed() throws SQLException {
      return this.isClosed;
   }

   public boolean isReadOnly() throws SQLException {
      return true;
   }

   public String nativeSQL(String sql) throws SQLException {
      return sql;
   }

   public CallableStatement prepareCall(String sql) throws SQLException {
      throw new NotImplementedException();
   }

   public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
      throw new NotImplementedException();
   }

   public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
      throw new NotImplementedException();
   }

   public PreparedStatement prepareStatement(String sql) throws SQLException {
      return new ZohoAnalyticsPreparedStatement(this, sql);
   }

   public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
      throw new NotImplementedException();
   }

   public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
      throw new NotImplementedException();
   }

   public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
      throw new NotImplementedException();
   }

   public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
      throw new NotImplementedException();
   }

   public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
      throw new NotImplementedException();
   }

   public void releaseSavepoint(Savepoint savepoint) throws SQLException {
      throw new NotImplementedException();
   }

   public void rollback() throws SQLException {
      throw new NotImplementedException();
   }

   public void rollback(Savepoint savepoint) throws SQLException {
      throw new NotImplementedException();
   }

   public void setAutoCommit(boolean commit) throws SQLException {
   }

   public void setCatalog(String catalog) throws SQLException {
      this.analyticsMetaData.switchWorkspace(catalog);
   }

   public void setHoldability(int holdability) throws SQLException {
   }

   public void setReadOnly(boolean read) throws SQLException {
   }

   public Savepoint setSavepoint() throws SQLException {
      throw new NotImplementedException();
   }

   public Savepoint setSavepoint(String savepoint) throws SQLException {
      throw new NotImplementedException();
   }

   public void setTransactionIsolation(int level) throws SQLException {
      throw new NotImplementedException();
   }

   public void setTypeMap(Map map) throws SQLException {
      throw new NotImplementedException();
   }

   private void checkClosed() throws SQLException {
      if (this.isClosed) {
         throw new SQLException("No operations allowed after connection closed");
      }
   }

   public Clob createClob() throws SQLException {
      throw new NotImplementedException();
   }

   public Blob createBlob() throws SQLException {
      throw new NotImplementedException();
   }

   public NClob createNClob() throws SQLException {
      throw new NotImplementedException();
   }

   public SQLXML createSQLXML() throws SQLException {
      throw new NotImplementedException();
   }

   public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
      throw new NotImplementedException();
   }

   public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
      throw new NotImplementedException();
   }

   public Properties getClientInfo() throws SQLException {
      throw new NotImplementedException();
   }

   public String getClientInfo(String name) throws SQLException {
      throw new NotImplementedException();
   }

   public void setClientInfo(Properties properties) throws SQLClientInfoException {
   }

   public void setClientInfo(String name, String value) throws SQLClientInfoException {
   }

   public boolean isValid(int timeout) throws SQLException {
      throw new NotImplementedException();
   }

   public void setSchema(String schema) throws SQLException {
      throw new NotImplementedException();
   }

   public String getSchema() throws SQLException {
      throw new NotImplementedException();
   }

   public void abort(Executor executor) throws SQLException {
      throw new NotImplementedException();
   }

   public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
      throw new NotImplementedException();
   }

   public int getNetworkTimeout() throws SQLException {
      throw new NotImplementedException();
   }
}
