title = About: ${Application.title} ${Application.version} 

closeAboutBox.Action.text = &Close

appDescLabel.text=<html>A simple Java desktop application for finding duplicates.

versionLabel.text=Product Version\:

homepageLabel.text=Author:

#NOI18N
imageLabel.icon=about.png