package com.adventnet.swissqlapi.sql.functions.date;

import com.adventnet.swissqlapi.sql.exception.ConvertException;
import com.adventnet.swissqlapi.sql.functions.FunctionCalls;
import com.adventnet.swissqlapi.sql.statement.select.SelectColumn;
import com.adventnet.swissqlapi.sql.statement.select.SelectQueryStatement;
import com.adventnet.swissqlapi.sql.statement.select.TableColumn;
import java.util.Vector;

public class dayofquarter extends FunctionCalls {
   public void toMySQL(SelectQueryStatement to_sqs, SelectQueryStatement from_sqs) throws ConvertException {
      this.functionName.setColumnName("");
      Vector arguments = new Vector();
      Vector vector1 = new Vector();
      Vector vector2 = new Vector();
      Vector vector3 = new Vector();
      Vector vector4 = new Vector();
      Vector vector5 = new Vector();

      for(int i_count = 0; i_count < this.functionArguments.size(); ++i_count) {
         if (this.functionArguments.elementAt(i_count) instanceof SelectColumn) {
            vector1.addElement(((SelectColumn)this.functionArguments.elementAt(i_count)).toMySQLSelect(to_sqs, from_sqs));
            vector2.addElement(((SelectColumn)this.functionArguments.elementAt(i_count)).toMySQLSelect(to_sqs, from_sqs));
            vector3.addElement(((SelectColumn)this.functionArguments.elementAt(i_count)).toMySQLSelect(to_sqs, from_sqs));
            vector4.addElement(((SelectColumn)this.functionArguments.elementAt(i_count)).toMySQLSelect(to_sqs, from_sqs));
            vector5.addElement(((SelectColumn)this.functionArguments.elementAt(i_count)).toMySQLSelect(to_sqs, from_sqs));
         } else {
            vector1.addElement(this.functionArguments.elementAt(i_count));
            vector2.addElement(this.functionArguments.elementAt(i_count));
            vector3.addElement(this.functionArguments.elementAt(i_count));
            vector4.addElement(this.functionArguments.elementAt(i_count));
            vector5.addElement(this.functionArguments.elementAt(i_count));
         }
      }

      SelectColumn sc_DayOfQuarter = new SelectColumn();
      Vector vc_DayOfQuarter = new Vector();
      SelectColumn sc_DateDiff = new SelectColumn();
      FunctionCalls fn_DateDiff = new FunctionCalls();
      TableColumn tb_DateDiff = new TableColumn();
      tb_DateDiff.setColumnName("DATEDIFF");
      fn_DateDiff.setFunctionName(tb_DateDiff);
      Vector vc_DateDiffIn = new Vector();
      Vector vc_DateDiffOut = new Vector();
      vc_DateDiffIn.addElement(vector1.get(0));
      SelectColumn sc_DatesubOfDay = new SelectColumn();
      FunctionCalls fn_DatesubOfDay = new FunctionCalls();
      TableColumn tb_DatesubOfDay = new TableColumn();
      tb_DatesubOfDay.setColumnName("DATE_SUB");
      fn_DatesubOfDay.setFunctionName(tb_DatesubOfDay);
      Vector vc_DateSubOfDayIn = new Vector();
      Vector vc_DateSubOfDayOut = new Vector();
      SelectColumn sc_DatesubOfMonth = new SelectColumn();
      FunctionCalls fnCall_DatesubOfMonth = new FunctionCalls();
      TableColumn tb_DatesubOfMonth = new TableColumn();
      tb_DatesubOfMonth.setColumnName("DATE_SUB");
      fnCall_DatesubOfMonth.setFunctionName(tb_DatesubOfMonth);
      Vector vc_datesubofmonthIn = new Vector();
      Vector vc_datsubofmonthOut = new Vector();
      vc_datesubofmonthIn.add(vector2.get(0));
      SelectColumn sc_value = new SelectColumn();
      Vector vc_value = new Vector();
      SelectColumn sc_month = new SelectColumn();
      FunctionCalls fn_month = new FunctionCalls();
      TableColumn tb_month = new TableColumn();
      tb_month.setColumnName("MONTH");
      fn_month.setFunctionName(tb_month);
      Vector vc_monthIn = new Vector();
      Vector vc_monthOut = new Vector();
      vc_monthIn.addElement(vector3.get(0));
      fn_month.setFunctionArguments(vc_monthIn);
      vc_monthOut.addElement(fn_month);
      sc_month.setColumnExpression(vc_monthOut);
      vc_value.add("INTERVAL ");
      vc_value.addElement("(");
      vc_value.addElement("(");
      vc_value.addElement(sc_month);
      vc_value.add("-");
      vc_value.add("1");
      vc_value.addElement(")");
      vc_value.add("%");
      vc_value.add("3");
      vc_value.addElement(")");
      vc_value.addElement(" MONTH");
      sc_value.setColumnExpression(vc_value);
      vc_datesubofmonthIn.addElement(sc_value);
      fnCall_DatesubOfMonth.setFunctionArguments(vc_datesubofmonthIn);
      vc_datsubofmonthOut.addElement(fnCall_DatesubOfMonth);
      sc_DatesubOfMonth.setColumnExpression(vc_datsubofmonthOut);
      vc_DateSubOfDayIn.addElement(sc_DatesubOfMonth);
      SelectColumn sc_value1 = new SelectColumn();
      Vector vc_value1 = new Vector();
      SelectColumn sc_day = new SelectColumn();
      FunctionCalls fn_day = new FunctionCalls();
      TableColumn tb_day = new TableColumn();
      tb_day.setColumnName("DAY");
      fn_day.setFunctionName(tb_day);
      Vector vc_dayIn = new Vector();
      Vector vc_dayOut = new Vector();
      SelectColumn sc_DatesubOfDayInterval = new SelectColumn();
      FunctionCalls fnCall_DatesubOfDayInterval = new FunctionCalls();
      TableColumn tb_DatesubOfDayInterval = new TableColumn();
      tb_DatesubOfDayInterval.setColumnName("DATE_SUB");
      fnCall_DatesubOfDayInterval.setFunctionName(tb_DatesubOfDayInterval);
      Vector vc_datesubofdayInDate = new Vector();
      Vector vc_datsubofdayOutDate = new Vector();
      vc_datesubofdayInDate.add(vector4.get(0));
      SelectColumn sc_month1 = new SelectColumn();
      FunctionCalls fn_month1 = new FunctionCalls();
      TableColumn tb_month1 = new TableColumn();
      tb_month1.setColumnName("MONTH");
      fn_month1.setFunctionName(tb_month1);
      Vector vc_monthIn1 = new Vector();
      Vector vc_monthOut1 = new Vector();
      vc_monthIn1.addElement(vector5.get(0));
      fn_month1.setFunctionArguments(vc_monthIn1);
      vc_monthOut1.addElement(fn_month1);
      sc_month1.setColumnExpression(vc_monthOut1);
      vc_value1.add("INTERVAL ");
      vc_value1.addElement("(");
      vc_value1.addElement("(");
      vc_value1.addElement(sc_month1);
      vc_value1.add("-");
      vc_value1.add("1");
      vc_value1.addElement(")");
      vc_value1.add("%");
      vc_value1.add("3");
      vc_value1.addElement(")");
      vc_value1.addElement(" MONTH");
      sc_value1.setColumnExpression(vc_value1);
      vc_datesubofdayInDate.addElement(sc_value1);
      fnCall_DatesubOfDayInterval.setFunctionArguments(vc_datesubofdayInDate);
      vc_datsubofdayOutDate.addElement(fnCall_DatesubOfDayInterval);
      sc_DatesubOfDayInterval.setColumnExpression(vc_datsubofdayOutDate);
      vc_dayIn.addElement(sc_DatesubOfDayInterval);
      fn_day.setFunctionArguments(vc_dayIn);
      vc_dayOut.addElement(fn_day);
      sc_day.setColumnExpression(vc_dayOut);
      SelectColumn sc_value2 = new SelectColumn();
      Vector vc_value2 = new Vector();
      vc_value2.add("INTERVAL");
      vc_value2.addElement("(");
      vc_value2.addElement(sc_day);
      vc_value2.add("-");
      vc_value2.add("1");
      vc_value2.addElement(")");
      vc_value2.add(" DAY");
      sc_value2.setColumnExpression(vc_value2);
      vc_DateSubOfDayIn.addElement(sc_value2);
      fn_DatesubOfDay.setFunctionArguments(vc_DateSubOfDayIn);
      vc_DateSubOfDayOut.addElement(fn_DatesubOfDay);
      sc_DatesubOfDay.setColumnExpression(vc_DateSubOfDayOut);
      vc_DateDiffIn.addElement(sc_DatesubOfDay);
      fn_DateDiff.setFunctionArguments(vc_DateDiffIn);
      vc_DateDiffOut.addElement(fn_DateDiff);
      sc_DateDiff.setColumnExpression(vc_DateDiffOut);
      vc_DayOfQuarter.addElement(sc_DateDiff);
      vc_DayOfQuarter.addElement("+");
      vc_DayOfQuarter.addElement("1");
      sc_DayOfQuarter.setColumnExpression(vc_DayOfQuarter);
      arguments.addElement(sc_DayOfQuarter);
      this.setFunctionArguments(arguments);
   }
}
