package com.adventnet.swissqlapi.sql.functions.date;

import com.adventnet.swissqlapi.sql.exception.ConvertException;
import com.adventnet.swissqlapi.sql.functions.FunctionCalls;
import com.adventnet.swissqlapi.sql.statement.select.SelectColumn;
import com.adventnet.swissqlapi.sql.statement.select.SelectQueryStatement;
import com.adventnet.swissqlapi.sql.statement.select.TableColumn;
import com.adventnet.swissqlapi.sql.statement.select.WhereColumn;
import com.adventnet.swissqlapi.sql.statement.select.WhereExpression;
import com.adventnet.swissqlapi.sql.statement.select.WhereItem;
import java.util.Vector;

public class islastnhour extends FunctionCalls {
   public void toMySQL(SelectQueryStatement to_sqs, SelectQueryStatement from_sqs) throws ConvertException {
      this.functionName.setColumnName("IF");
      Vector vc_islastnhrArgs = new Vector();
      Vector vector1 = new Vector(1);
      Vector vector2 = new Vector(1);

      for(int i_count = 0; i_count < this.functionArguments.size(); ++i_count) {
         if (this.functionArguments.elementAt(i_count) instanceof SelectColumn) {
            vector1.addElement(((SelectColumn)this.functionArguments.elementAt(i_count)).toMySQLSelect(to_sqs, from_sqs));
            vector2.addElement(((SelectColumn)this.functionArguments.elementAt(i_count)).toMySQLSelect(to_sqs, from_sqs));
         } else {
            vector1.addElement(this.functionArguments.elementAt(i_count));
            vector2.addElement(this.functionArguments.elementAt(i_count));
         }
      }

      WhereExpression whereExpression = new WhereExpression();
      WhereItem whereItem_0 = new WhereItem();
      WhereColumn whColumn_whItem0_left = new WhereColumn();
      Vector whColumn_whItem0_left_vec = new Vector();
      FunctionCalls fnCl_datesub1 = new FunctionCalls();
      TableColumn tbCl_datesub1 = new TableColumn();
      tbCl_datesub1.setColumnName("DATE_SUB");
      fnCl_datesub1.setFunctionName(tbCl_datesub1);
      Vector fnCl_datesub1_args = new Vector();
      SelectColumn sc_curr_tstamp = new SelectColumn();
      FunctionCalls fnCl_sc_curr_tstamp = new FunctionCalls();
      TableColumn tbCl_sc_curr_tstamp = new TableColumn();
      tbCl_sc_curr_tstamp.setColumnName("current_timestamp");
      fnCl_sc_curr_tstamp.setFunctionName(tbCl_sc_curr_tstamp);
      Vector sc_curr_tstamp_vc = new Vector();
      sc_curr_tstamp_vc.addElement(fnCl_sc_curr_tstamp);
      sc_curr_tstamp.setColumnExpression(sc_curr_tstamp_vc);
      fnCl_datesub1_args.addElement(sc_curr_tstamp);
      SelectColumn sc_inter_n_hr = new SelectColumn();
      TableColumn tbCl_sc_inter_n_hr = new TableColumn();
      tbCl_sc_inter_n_hr.setColumnName("interval");
      Vector sc_interval_n_hr_vec = new Vector();
      sc_interval_n_hr_vec.addElement(tbCl_sc_inter_n_hr);
      SelectColumn intrVal = (SelectColumn)vector1.get(1);
      intrVal.setOpenBrace("(");
      intrVal.setCloseBrace(")");
      sc_interval_n_hr_vec.addElement(intrVal);
      sc_interval_n_hr_vec.add("hour");
      sc_inter_n_hr.setColumnExpression(sc_interval_n_hr_vec);
      fnCl_datesub1_args.addElement(sc_inter_n_hr);
      fnCl_datesub1.setFunctionArguments(fnCl_datesub1_args);
      whColumn_whItem0_left_vec.addElement(fnCl_datesub1);
      whColumn_whItem0_left.setColumnExpression(whColumn_whItem0_left_vec);
      whereItem_0.setLeftWhereExp(whColumn_whItem0_left);
      WhereColumn whColumn_whItem0_right = new WhereColumn();
      Vector whColumn_whItem0_right_vec = new Vector();
      FunctionCalls fnCl_tstamp = new FunctionCalls();
      TableColumn tbCl_fnCl_tstamp = new TableColumn();
      tbCl_fnCl_tstamp.setColumnName("timestamp");
      fnCl_tstamp.setFunctionName(tbCl_fnCl_tstamp);
      Vector fnCl_timestamp_args = new Vector();
      SelectColumn sl_concat_currdate_col = new SelectColumn();
      Vector fnCl_concat_currdate_col_args = new Vector();
      FunctionCalls fnCl_concat_currdate_col = new FunctionCalls();
      TableColumn tbCl_fnCl_concat_currdate_col = new TableColumn();
      tbCl_fnCl_concat_currdate_col.setColumnName("concat");
      fnCl_concat_currdate_col.setFunctionName(tbCl_fnCl_concat_currdate_col);
      SelectColumn sc_current_date = new SelectColumn();
      FunctionCalls fnCl_sc_current_date = new FunctionCalls();
      TableColumn tbCl_fnCl_sc_current_date = new TableColumn();
      tbCl_fnCl_sc_current_date.setColumnName("current_date");
      fnCl_sc_current_date.setFunctionName(tbCl_fnCl_sc_current_date);
      Vector sc_current_date_vc = new Vector();
      sc_current_date_vc.addElement(fnCl_sc_current_date);
      sc_current_date.setColumnExpression(sc_current_date_vc);
      fnCl_concat_currdate_col_args.addElement(sc_current_date);
      Vector emptyStrVec = new Vector();
      emptyStrVec.addElement("' '");
      SelectColumn sc_emptyStr = new SelectColumn();
      sc_emptyStr.setColumnExpression(emptyStrVec);
      fnCl_concat_currdate_col_args.addElement(sc_emptyStr);
      SelectColumn sc_time_col = new SelectColumn();
      FunctionCalls fnCl_sc_time_col = new FunctionCalls();
      TableColumn tbCl_fnCl_sc_time_col = new TableColumn();
      tbCl_fnCl_sc_time_col.setColumnName("time");
      fnCl_sc_time_col.setFunctionName(tbCl_fnCl_sc_time_col);
      Vector time_col_args = new Vector();
      time_col_args.addElement(vector1.get(0));
      fnCl_sc_time_col.setFunctionArguments(time_col_args);
      Vector sc_time_col_vc = new Vector();
      sc_time_col_vc.addElement(fnCl_sc_time_col);
      sc_time_col.setColumnExpression(sc_time_col_vc);
      fnCl_concat_currdate_col_args.addElement(sc_time_col);
      fnCl_concat_currdate_col.setFunctionArguments(fnCl_concat_currdate_col_args);
      Vector fnCl_concat_currdate_col_vc = new Vector();
      fnCl_concat_currdate_col_vc.addElement(fnCl_concat_currdate_col);
      sl_concat_currdate_col.setColumnExpression(fnCl_concat_currdate_col_vc);
      fnCl_timestamp_args.addElement(sl_concat_currdate_col);
      fnCl_tstamp.setFunctionArguments(fnCl_timestamp_args);
      whereItem_0.setOperator("<=");
      whColumn_whItem0_right_vec.addElement(fnCl_tstamp);
      whColumn_whItem0_right.setColumnExpression(whColumn_whItem0_right_vec);
      whereItem_0.setRightWhereExp(whColumn_whItem0_right);
      WhereItem whereItem_1 = new WhereItem();
      WhereColumn whColwhIt1_ltExp = new WhereColumn();
      Vector vc_whColwhIt1_ltExp = new Vector();
      new SelectColumn();
      FunctionCalls fnCl_timestamp_whit1 = new FunctionCalls();
      TableColumn tbCl_fnCl_timestamp_whit1 = new TableColumn();
      tbCl_fnCl_timestamp_whit1.setColumnName("timestamp");
      fnCl_timestamp_whit1.setFunctionName(tbCl_fnCl_tstamp);
      Vector fnCl_timestamp_args_whit1 = new Vector();
      SelectColumn sl_concat_currdate_col_whit1 = new SelectColumn();
      Vector fnCl_concat_cdate_col_args_whit1 = new Vector();
      FunctionCalls fnCl_concat_currdate_col_whit1 = new FunctionCalls();
      TableColumn tbCl_fnCl_concat_currdate_col_whit1 = new TableColumn();
      tbCl_fnCl_concat_currdate_col_whit1.setColumnName("concat");
      fnCl_concat_currdate_col_whit1.setFunctionName(tbCl_fnCl_concat_currdate_col);
      SelectColumn sc_current_date_whit1 = new SelectColumn();
      FunctionCalls fnCl_sc_current_date_whit1 = new FunctionCalls();
      TableColumn tbCl_fnCl_sc_current_date_whit1 = new TableColumn();
      tbCl_fnCl_sc_current_date_whit1.setColumnName("current_date");
      fnCl_sc_current_date_whit1.setFunctionName(tbCl_fnCl_sc_current_date_whit1);
      Vector sc_current_date_whit1_vc = new Vector();
      sc_current_date_whit1_vc.addElement(fnCl_sc_current_date_whit1);
      sc_current_date_whit1.setColumnExpression(sc_current_date_whit1_vc);
      fnCl_concat_cdate_col_args_whit1.addElement(sc_current_date_whit1);
      Vector emptyStrVec_whit1 = new Vector();
      emptyStrVec_whit1.addElement("' '");
      SelectColumn sc_emptyStr_whit1 = new SelectColumn();
      sc_emptyStr_whit1.setColumnExpression(emptyStrVec_whit1);
      fnCl_concat_cdate_col_args_whit1.addElement(sc_emptyStr_whit1);
      SelectColumn sc_time_col_whit1 = new SelectColumn();
      FunctionCalls fnCl_sc_time_col_whit1 = new FunctionCalls();
      TableColumn tbCl_fnCl_sc_time_col_whit1 = new TableColumn();
      tbCl_fnCl_sc_time_col_whit1.setColumnName("time");
      fnCl_sc_time_col_whit1.setFunctionName(tbCl_fnCl_sc_time_col_whit1);
      Vector time_col_args_whit1 = new Vector();
      time_col_args_whit1.addElement(vector2.get(0));
      fnCl_sc_time_col_whit1.setFunctionArguments(time_col_args_whit1);
      Vector sc_time_col_whit1_vc = new Vector();
      sc_time_col_whit1_vc.addElement(fnCl_sc_time_col_whit1);
      sc_time_col_whit1.setColumnExpression(sc_time_col_whit1_vc);
      fnCl_concat_cdate_col_args_whit1.addElement(sc_time_col_whit1);
      fnCl_concat_currdate_col_whit1.setFunctionArguments(fnCl_concat_cdate_col_args_whit1);
      Vector sl_concat_currdate_col_whit1_vc = new Vector();
      sl_concat_currdate_col_whit1_vc.addElement(fnCl_concat_currdate_col_whit1);
      sl_concat_currdate_col_whit1.setColumnExpression(sl_concat_currdate_col_whit1_vc);
      fnCl_timestamp_args_whit1.addElement(sl_concat_currdate_col_whit1);
      fnCl_timestamp_whit1.setFunctionArguments(fnCl_timestamp_args_whit1);
      vc_whColwhIt1_ltExp.addElement(fnCl_timestamp_whit1);
      whColwhIt1_ltExp.setColumnExpression(vc_whColwhIt1_ltExp);
      whereItem_1.setLeftWhereExp(whColwhIt1_ltExp);
      WhereColumn whColwhIt1_rtExp = new WhereColumn();
      Vector vc_whColwhIt1_rtExp = new Vector();
      vc_whColwhIt1_rtExp.addElement(sc_curr_tstamp);
      whColwhIt1_rtExp.setColumnExpression(vc_whColwhIt1_rtExp);
      whereItem_1.setRightWhereExp(whColwhIt1_rtExp);
      whereItem_1.setOperator("<=");
      whereExpression.addWhereItem(whereItem_0);
      whereExpression.addWhereItem(whereItem_1);
      Vector whExp_op = new Vector();
      whExp_op.addElement("AND");
      whereExpression.setOperator(whExp_op);
      SelectColumn sc_whIt = new SelectColumn();
      Vector vc_whExp = new Vector();
      vc_whExp.addElement(whereExpression);
      sc_whIt.setColumnExpression(vc_whExp);
      SelectColumn sc_trueStmt = new SelectColumn();
      Vector vc_trueStmt = new Vector();
      vc_trueStmt.addElement("1");
      sc_trueStmt.setColumnExpression(vc_trueStmt);
      SelectColumn sc_falseStmt = new SelectColumn();
      Vector vc_falseStmt = new Vector();
      vc_falseStmt.addElement("0");
      sc_falseStmt.setColumnExpression(vc_falseStmt);
      vc_islastnhrArgs.addElement(sc_whIt);
      vc_islastnhrArgs.addElement(sc_trueStmt);
      vc_islastnhrArgs.addElement(sc_falseStmt);
      this.setFunctionArguments(vc_islastnhrArgs);
   }
}
