db.url=jdbc:oracle:thin:@usatler01:1521/orclpdb.csl.local
db.username=ucompiere
db.password=ucompiere
file.inbound=\\Usatler01\\pl\\eInvoices\\Inbound
file.iboundArcheive=\\Usatler01\\pl\\Invoices
file.destination=USATLER01.csl.local